// Real WASM pointer ownership, typography, editable bindings, and formula carets.
const {chromium}=require(process.env.QURSO_PLAYWRIGHT||'../work/e2e/node_modules/playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const evidence=path.resolve('work/e2e/evidence');fs.mkdirSync(evidence,{recursive:true});
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.QURSO_TEST_BROWSER,args:['--enable-unsafe-webgpu','--use-angle=swiftshader']});
 const context=await browser.newContext({viewport:{width:1280,height:720},permissions:['clipboard-read','clipboard-write']});
 await context.addInitScript(()=>localStorage.setItem('drafftink.user_settings.v1',JSON.stringify({restore_last_document:false,autosave_enabled:false,intro_json:'',default_font:'Noto Sans',default_font_postscript:'',hide_properties:true})));
 const page=await context.newPage();
 const state=()=>page.evaluate(()=>JSON.parse(window.__drafftinkTestState));
 const wait=async predicate=>{for(let i=0;i<160;i++){const s=await state().catch(()=>null);if(s&&predicate(s))return s;await page.waitForTimeout(100);}throw Error('UI32 timeout: '+JSON.stringify(await state()));};
 const click=async name=>{const s=await wait(s=>s.controls[name]);const r=s.controls[name];await page.mouse.move((r[0]+r[2])/2,(r[1]+r[3])/2);await page.waitForTimeout(120);await page.mouse.click((r[0]+r[2])/2,(r[1]+r[3])/2,{delay:70});await page.waitForTimeout(120);};
 const menu=async()=>{await page.mouse.move(28,28);await page.waitForTimeout(120);await page.mouse.click(28,28,{delay:70});await wait(s=>s.controls['Menu Settings']);};
 const key=async value=>{await page.keyboard.press(value);await page.waitForTimeout(130);};
 try {
  await page.goto((process.env.QURSO_TEST_URL||'http://127.0.0.1:8888/')+'?drafftink-test=1');await wait(s=>s.shapes.length===0);
  await key('d');await wait(s=>s.tool==='Freehand');
  await menu();
  const settingsRow=(await state()).controls['Menu Settings'];
  assert(Math.abs(settingsRow[3]-settingsRow[1]-28)<1,'Settings must be a normal menu row');
  await click('Menu Settings');await wait(s=>s.controls['Settings panel']);
  await page.mouse.move(1100,470);await page.waitForTimeout(100);
  await page.mouse.down();await page.mouse.move(1180,540,{steps:8});await page.waitForTimeout(150);
  let s=await state();assert(s.controls['Settings panel']&&s.shapes.length===0,'Settings must block a held outside drag');
  await page.mouse.up();await key('Escape');await wait(s=>!s.controls['Settings panel']);
  await menu();await page.mouse.move(700,420);await page.waitForTimeout(120);await page.mouse.down();
  await wait(s=>!s.controls['Menu Settings']);await page.mouse.move(820,510,{steps:8});await page.mouse.up();
  assert.equal((await state()).shapes.length,0,'Dismissing a menu on mouse-down must not begin drawing');
  await key('r');await wait(s=>s.tool==='Rectangle');
  await page.mouse.move(350,260);await page.waitForTimeout(100);await page.mouse.down();await page.mouse.move(520,370,{steps:8});await page.mouse.up();await wait(s=>s.shapes.length===1&&s.selected_count===1);
  await key('Control+l');await wait(s=>s.shapes[0].pinned);
  await key('Control+l');await wait(s=>!s.shapes[0].pinned);
  await menu();await click('Menu Shortcuts');await wait(s=>s.controls['Shortcuts panel']);
  assert((await state()).controls['Shortcut pin'],'Pin must be documented and editable');
  assert((await state()).controls['Shortcut reset_panels'],'Panel reset shortcut must be documented');
  let pinRect=(await state()).controls['Shortcut pin'];
  while(pinRect[1]>580||pinRect[1]<95){await page.mouse.move(600,350);await page.mouse.wheel(0,pinRect[1]>580?280:-280);await page.waitForTimeout(200);pinRect=(await state()).controls['Shortcut pin'];}
  await click('Shortcut pin');await key('Control+a');await page.keyboard.type('Alt+L');
  await click('Shortcuts save');await wait(s=>!s.controls['Shortcuts panel']);
  const stored=await page.evaluate(()=>JSON.parse(localStorage.getItem('drafftink.user_settings.v1')));
  assert.equal(stored.shortcut_overrides.pin,'Alt+L');
  await page.mouse.move(700,430);await page.waitForTimeout(100);await key('Control+l');assert(!(await state()).shapes[0].pinned,'Rebound default must no longer execute');
  await key('Alt+l');await wait(s=>s.shapes[0].pinned);await key('Alt+l');await wait(s=>!s.shapes[0].pinned);
  await menu();await click('Menu Settings');await click('Settings tab Data');await click('Config Reset');await wait(s=>!s.controls['Settings panel']);
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('drafftink.user_settings.v1')).shortcut_overrides),{});
  await click('New canvas');await wait(s=>s.shapes.length===0);
  await click('tool_Insert');
  const chooserEvent=page.waitForEvent('filechooser');await click('Insert Image');
  await (await chooserEvent).setFiles('work/e2e/fixtures/image-1200x2000.png');await wait(s=>s.shapes.some(x=>x.shape.Image));
  await key('s');await page.mouse.move(420,375);await page.waitForTimeout(150);await page.mouse.click(420,375,{delay:70});await wait(s=>s.selected_count===1);
  await key('Control+l');await wait(s=>s.shapes[0].pinned);
  await page.mouse.click(420,375,{button:'right',delay:70});await wait(s=>s.context_properties&&s.controls['Pinned background']);
  await click('Pinned background');await click('Pinned custom');
  s=await wait(s=>s.controls['Pinned picker controls']&&s.controls['Properties panel']);
  const picker=s.controls['Pinned picker controls'],properties=s.controls['Properties panel'];
  assert(Math.abs((s.controls['Pinned palette'][0]+s.controls['Pinned palette'][2]-properties[0]-properties[2])/2)<5,'Pinned palette should be centered on Properties');
  const point=[picker[0]+55,Math.max(picker[1]+95,properties[3]+18)];
  assert(point[1]<picker[3]-30,'Picker extends below Properties and its square/hue remains interactive');
  assert(point[1]>properties[3]||point[1]<properties[1]||point[0]<properties[0]||point[0]>properties[2],'Exercise the picker outside the Properties rectangle');
  const before=s.shapes[0].shape.Image;
  const oldBg=JSON.stringify(s.shapes[0].pinned_background);
  await page.mouse.move(...point);await page.waitForTimeout(120);await page.mouse.down();await page.mouse.move(point[0]+35,point[1]+15,{steps:6});await page.mouse.up();
  s=await wait(s=>s.controls['Pinned picker controls']&&s.context_properties&&JSON.stringify(s.shapes[0].pinned_background)!==oldBg);
  assert.deepEqual(s.shapes[0].shape.Image,before,'Picking a background must not resize or alter the image');
  await page.screenshot({path:path.join(evidence,'pinned-picker-white.png')});
  await key('Escape');await page.mouse.move(600,400);await page.waitForTimeout(120);await key('Control+z');await wait(s=>JSON.stringify(s.shapes[0].pinned_background)===oldBg);
  await click('New canvas');await wait(s=>s.shapes.length===0);
  await key('t');await page.mouse.move(350,260);await page.waitForTimeout(120);await page.mouse.click(350,260,{delay:70});await wait(s=>s.editing_text);
  for(const c of 'frac(')await page.keyboard.press(c);await wait(s=>s.command_editor==='frac('&&s.controls['Code formule']);await page.waitForTimeout(150);
  for(const c of '123,7895)')await page.keyboard.press(c);
  s=await wait(s=>s.command_editor==='frac(123,7895)'&&s.formula_caret);
  const endCaret=s.formula_caret;
  await key('Home');for(let i=0;i<12;i++)await key('ArrowRight');
  s=await wait(s=>s.command_caret===12&&s.formula_caret&&s.formula_caret[0]<endCaret[0]-2);
  const inside=s.formula_caret;assert(inside[1]>endCaret[1],'Denominator caret must follow its baseline');
  await page.screenshot({path:path.join(evidence,'fraction-source-caret.png')});
  await key('Escape');await wait(s=>!s.editing_text);await click('New canvas');await wait(s=>s.shapes.length===0);
  await click('tool_Insert');await click('Insert Time');
  s=await wait(s=>s.time_widgets?.length===1);
  const id=s.time_widgets[0].id;
  const widget=()=>state().then(s=>s.controls[`Time widget ${id}`]);
  let rect=await widget();await page.mouse.move((rect[0]+rect[2])/2,(rect[1]+rect[3])/2);await page.waitForTimeout(150);await page.mouse.click((rect[0]+rect[2])/2,(rect[1]+rect[3])/2,{delay:70});
  await click(`Time options ${id}`);await click(`Time font ${id}`);await click(`Time font ${id} Inter`);await wait(s=>s.time_widgets[0].font===1);
  await click(`Time options close ${id}`);await key('d');
  rect=await widget();await page.mouse.move((rect[0]+rect[2])/2,(rect[1]+rect[3])/2);await page.waitForTimeout(150);
  const corner=(await state()).controls[`Time resize ${id} 3`];
  await page.mouse.move(corner[2]-2,(corner[1]+corner[3])/2);await page.waitForTimeout(250);
  const cursor=await page.evaluate(()=>document.querySelector('canvas').style.cursor);
  assert(cursor.includes('resize'),'Full Time resize hit area must show a resize cursor');
  await click(`Time play ${id}`);await wait(s=>s.time_widgets[0].running);await page.waitForTimeout(200);
  const a=await state();await page.waitForTimeout(700);const b=await state();
  for(let index=0;index<8;index++)assert.deepEqual(a.controls[`Time digit ${id} ${index}`],b.controls[`Time digit ${id} ${index}`],'Digit columns must not move as values change');
  assert.equal(a.canvas_render_count,b.canvas_render_count,'Timer animation must reuse the unchanged canvas texture');
  await page.screenshot({path:path.join(evidence,'time-inter-stable.png')});
  console.log('UI32 checks passed: modal/menu gestures, white pinned picker overflow, Undo, editable pin binding, config reset, source caret, Inter digits and resize cursor, UI-only redraw.');
 }catch(error){await page.screenshot({path:path.join(evidence,'ui32-failure.png')});fs.writeFileSync(path.join(evidence,'ui32-failure-state.json'),JSON.stringify(await state(),null,2));throw error;}finally{await browser.close();}
})().catch(error=>{console.error(error);process.exitCode=1;});
